---
title: "HW5"
author: "Chong Zhang"
date: "November 26, 2018"
output: html_document
---

```{r cache=TRUE}
library(dplyr)
library(ggplot2)
library(glmnet)
library(MASS)
library(car)
library(corrplot)


load(file = 'AmesHousing.RData')
attach(house)
scatterplotMatrix(~SalePrice+MS.Zoning+Lot.Area+Lot.Shape+Land.Contour,data = house, smooth=FALSE)
scatterplotMatrix(~SalePrice+Neighborhood+Condition.1+Bldg.Type+House.Style,data = house, smooth=FALSE)
scatterplotMatrix(~SalePrice+Overall.Qual+Overall.Cond+Year.Built+Year.Remod.Add, smooth=FALSE)
scatterplotMatrix(~SalePrice+Roof.Style++Mas.Vnr.Type+Mas.Vnr.Area+Exter.Qual,data = house, smooth=FALSE)
scatterplotMatrix(~SalePrice+Exter.Cond+Foundation+Bsmt.Qual+Bsmt.Cond,data = house, smooth=FALSE)
scatterplotMatrix(~SalePrice+BsmtFin.SF+Total.Bsmt.SF+Heating.QC+Central.Air, data = house, smooth=FALSE)
scatterplotMatrix(~SalePrice+X1st.Flr.SF+Gr.Liv.Area+Bedroom.AbvGr+Kitchen.Qual,data = house, smooth=FALSE)
scatterplotMatrix(~SalePrice+TotRms.AbvGrd+Fireplaces+Fireplace.Qu+Garage.Type,data = house, smooth=FALSE)
scatterplotMatrix(~SalePrice+Garage.Finish+Garage.Cars+Garage.Area+Paved.Drive,data = house, smooth=FALSE)
scatterplotMatrix(~SalePrice+Wood.Deck.SF+Open.Porch.SF+Enclosed.Porch+X3Ssn.Porch,data = house, smooth=FALSE)
scatterplotMatrix(~SalePrice+Screen.Porch+Pool.Area+Fence+Sale.Type,data = house, smooth=FALSE)
scatterplotMatrix(~SalePrice+Sale.Condition+Yr.Sold+Bath,data = house, smooth=FALSE)

```

The distribution of SalePrice is hightly skewed. There are couple of predicting variables shows high level of linearality with SalePrice. Some do not show significant level of linearity. 

(b)

```{r cache=TRUE}
X = model.matrix(lm(SalePrice~., data = house))[,-1]
X = cbind(SalePrice, X)
corrplot(cor(X), tl.cex = 0.1)


```